apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: credentialsrequests.cloudcreds.openshift.io
spec:
  group: cloudcreds.openshift.io
  names:
    kind: CredentialsRequest
    plural: credentialsrequests
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            aws:
              properties:
                statementEntries:
                  items:
                    properties:
                      action:
                        items:
                          type: string
                        type: array
                      effect:
                        type: string
                      resource:
                        type: string
                    required:
                    - effect
                    - action
                    - resource
                    type: object
                  type: array
              required:
              - statementEntries
              type: object
            clusterID:
              type: string
            clusterName:
              type: string
            secret:
              type: object
          required:
          - clusterName
          - clusterID
          - secret
          type: object
        status:
          properties:
            aws:
              properties:
                accessKeyID:
                  type: string
                user:
                  type: string
              required:
              - user
              - accessKeyID
              type: object
            lastSyncGeneration:
              format: int64
              type: integer
            lastSyncTimestamp:
              format: date-time
              type: string
            provisioned:
              type: boolean
          required:
          - provisioned
          - lastSyncGeneration
          type: object
      required:
      - spec
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
