apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-credential-operator-role
  namespace: openshift-config-managed
  annotations:
    capability.openshift.io/name: CloudCredential
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - kube-cloud-config
  verbs:
  - "get"
