apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: cloud-credential
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"

