apiVersion: credminter.openshift.io/v1beta1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-image-registry
spec:
  clusterName: mycluster
  clusterID: 97216809-bff7-4ea8-b07e-3dec2a0aa4d4
  secretRef:
    name: installer-cloud-credentials
    namespace: myproject
#    namespace: openshift-image-registry
  aws:
    statementEntries:
    - effect: Allow
      action:
      - s3:CreateBucket
      - s3:DeleteBucket
      resource: "*"
---

